name: Daily Tech News Digest

on:
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST (03:30 UTC)
  workflow_dispatch:       # Allow manual trigger

jobs:
  send-news:
    runs-on: ubuntu-latest

    env:
      NEWSDATA_API_KEY: ${{ secrets.NEWS_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-generativeai

      - name: Run Daily Tech News Bot
        run: python daily_tech_news_bot.py
