name: Daily Tech News Digest

on:
  schedule:
    - cron: '30 3 * * *' # 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:

jobs:
  run-news-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install google-generativeai requests

      - name: Run news digest bot
        env:
          NEWSDATA_API_KEY: ${{ secrets.NEWS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python daily_tech_news_bot.py
