name: Send Tech News to Telegram

on:
  schedule:
    - cron: "00 4 * * *"  # runs daily at 8 AM UTC (adjust to your timezone)
  workflow_dispatch:

jobs:
  send_news:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
      NEWSDATA_API_KEY: ${{ secrets.NEWS_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install transformers torch requests

      - name: Run tech news bot
        run: python daily_tech_news_bot.py
