name: Daily Tech News Bot

on:
  schedule:
    - cron: '00 4 * * *'  # Runs daily at 5:00 AM UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies without requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv transformers torch

      - name: Run the bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          python daily_tech_news_bot.py
